export const ActionTypes = {
  SET_RECIPES: "SET_RECIPES",
  EDIT_RECIPE: "EDIT_RECIPE",
  REMOVE_RECIPE: "REMOVE_RECIPE",
  ADD_FAVORITE_RECIPE: "ADD_FAVORITE_RECIPE",
  REMOVE_FAVORITE_RECIPE: "REMOVE_FAVORITE_RECIPE",
  FAVORITE_REMOVE_RECEIPE: "FAVORITE_REMOVE_RECEIPE",

  REMOVE_FROM_FAVORITE_RECIPE: "REMOVE_FROM_FAVORITE_RECIPE",
  ADD_UNFAVORITE_TO_ALL_RECIPE: "ADD_UNFAVORITE_TO_ALL_RECIPE",

  ADD_SIGNUP: "ADD_SIGNUP",
  ADD_LOGIN: "ADD_LOGIN",
  ADD_LOGOUT: "ADD_LOGOUT",
};
